services:
  app:
    image: spanish-idioms-spring
    ports:
      - ${SPRING_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_SERVER_ADDRESS: ${SPRING_SERVER_ADDRESS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      AI_MODEL: ${AI_MODEL}
      API: ${API}
      SPRING_NETWORK_PORT: ${SPRING_NETWORK_PORT}
    depends_on:
      - mysql

  mysql:
    image: 'mysql:latest'
    volumes:
      - spanishidioms_mysql-data:${DB_DATA_DIR}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      MYSQL_USER: ${SPRING_DATASOURCE_USERNAME}
    ports:
      - ${DATABASE_PORT}

volumes:
  spanishidioms_mysql-data:
    external: true
